### PR TITLE
Reorder joint names for joint-based trajectories

### LINKED ISSUE #4: foward_joint_traj_controller does not take into account sequence of joints defined in trajectory #beta-testing
After setting up and testing pass_through controllers we experienced some weird behaviour through MoveIt and also while executing our prerecorded trajectory. The issue is that the sequence of the joints which is defined in the trajectory is not taken into account. The sequence of joint names in our prerecorded trajectory was following: elbow_joint, shoulder_pan_joint, shoulder_lift_joint, wrist1, wrist2, wrist3 and the values of positions in respective order. 

It seems that the controller takes the first value assuming that it is the shoulder_pan_joint, but in reality, in this case, this was elbow_joint. And this of course explained the weird behaviour.

After manually modifying position values so that the shoulder_pan_joint comes first, the trajectory was executed correctly. We also tried the same setup with scaled_pos_joint_traj_controller, where joint names are taken into account.

### PR DESCRIPTION
**Pull request by stefanscherzinger**
**Goal**:
MoveIt generates joint trajectories with alphabetic joint order.
This fix takes that into consideration and reorders the joints and
associated data fields in the joint trajectory message according to
a specified joint order.

These changes are best placed into the trajectory interface where a
type-based distinction is easier than in
PassThroughControllers.

Fixes #4 

**Possible next steps**:
There are two places where the joint names could be set for trajectory interfaces:

1) As currently done in the PassThroughControllers [here](https://github.com/fzi-forschungszentrum-informatik/cartesian_ros_control/blob/master/pass_through_controllers/include/pass_through_controllers/pass_through_controllers.hpp#L77) after the controller got the trajectory interface from the HW (just before getting a handle for writing commands).
The rational would be: _Users best known what joints their forwarding controller should operate on and in which order they are given. Different controllers can allow different joint combinations. There is no sanity check whether that's feasible with the driver_.

2) In the HWInterface, e.g. right after [this line](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/beta-testing/ur_robot_driver/src/hardware_interface.cpp#L340):
```c++
jnt_traj_interface_.setJointNames(joint_names_);
```
The rational would be: _Implementers of the driver best known what joints the trajectory interfaces will claim and in which order.  The forwarding controllers are valid for this specification. Users do not specify joints for them_.

With the second option, we then only have _one place_ where to specify the correct joint order: 
```yaml
# Settings for ros_control hardware interface
     ur_hardware_interface:
          joints: &robot_joints
             - shoulder_pan_joint
             - shoulder_lift_joint
             - elbow_joint
             - wrist_1_joint
             - wrist_2_joint
             - wrist_3_joint
```
(at least in theory. There seem to be various places in the ur*_controllers.yaml files :)

### CODE REVIEW

**Comment by stefanscherzinger** [comment]
@fmauch What do you think?

**Comment by gavanderhoorn** [comment]
> The rational would be: _Implementers of the driver best known what joints the trajectory interfaces will claim and in which order_

is this really true?

I've written quite some `hardware_interface`s, but never know which controllers users will be configuring them with.

The rationale for the second option seems to imply driver authors should know that?

**Comment by fmauch** [comment]
I think what @stefanscherzinger meant is that the HW interface knows which joint it could *potentially* be controlling and in which order they should be sent.

Writing this I realize, that there might not be a required joint order, e.g. if there's a communication protocol with named fields involved (for example XML-based). The order only matters if we have a plain number-array interface to the robot. This might actually be an argument for the implementation in https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/345...

I'm sorry, I'm just realizing this now, as I have been voting for this implementation.

**Comment by gavanderhoorn** [comment]
> I think what @stefanscherzinger meant is that the HW interface knows which joint it could _potentially_ be controlling and in which order they should be sent.

forgive me for being slow, but how does that help?

for hw ifaces which require a certain order, that order is known by the hw iface. *Always* I would almost say.

For those that don't, the order is not important.

**Comment by fmauch** [comment]
> for hw ifaces which require a certain order, that order is known by the hw iface. _Always_ I would almost say.
> 
> For those that don't, the order is not important.

Yes, that was my point risen. We decided to move joint ordering to the controller interface so that HW interface implementations would not have to implement joint reordering every time by themselves. However, that was under the (obviously wrong) assumption, that joint ordering would matter for all of them. As this is in fact not the case, the solution proposed in https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/345 might be the better choice, after all.

**Comment by gavanderhoorn** [comment]
Hm. Proliferating all of this to hw interfaces is rather unfortunate, but perhaps the easiest approach for now.

**Comment by gavanderhoorn** [comment]
What's the problem btw with always making sure the order is as configured (ie: doing this in the interface), even if the underlying hw iface doesn't require it?

Doesn't seem like a huge amount of overhead, and would seem to solve the problem.

**Comment by stefanscherzinger** [comment]
I'll draw a conclusion:
Let's use _this_ PR for the following reasons:
- We avoid the need for HW implementers to reimplement joint ordering for their robot
- If their robot _does allow_ for mixed-up joint ordering, then there's no harm in having ordered them anyway
- We let users specify the joints (and order) for the PassThroughControllers (_place 1._ of **Possible next steps** )

**Pull request merged**
